.TH CHMPXSTATUS "1" "Mar 2018" "CHMPX" "Consistent Hashing Mq inProcess data eXchange"
.SH NAME
CHMPXSTATUS \- Check local chmpx node status Tool for CHMPX
.SH SYNOPSIS
.B chmpxstatus [options]
.SH DESCRIPTION
.PP
chmpxstatus is checking chmpx status tool, this attaches shared memory on local host which is made by chmpx. Then this tool check and dump local chmpx status. You can see usage this tool by typing "-h".
.SH OPTIONS
.TP
\fB\-h\fR
display help
.TP
\fB\-conf\ [file\ path]\fR
specify configuration file(.ini .yaml .json) which is same file for CHMPX server/slave node.
.TP
\fB\-json\ [json\ string]\fR
specify configuration json string which is same file for CHMPX server/slave node.
.TP
\fB\-ctlport\ [control\ port\ number]\fR
specify the self control port. if ctlport option is specified, chmpx searches same ctlport in configuration and ignores "CTLPORT" directive in "GLOBAL" section. and chmpx will start in the mode indicated by the server entry that has been detected.
.TP
\fB\-d\fR\ [SILENT\ |\ ERR\ |\ WAN\ |\ INFO\ |\ DUMP]\fR
specify debugging level, chmpx displays debugging message for itself.
.TP
\fB\-dfile\ [debug\ file\ path]\fR
specify file path for output debugging messages.
.SH SEE ALSO
.TP
chmpx(1)
.SH BUGS
.TP
Please report owner and committer.
.SH AUTHOR
chmpxstatus has been written by Takeshi Nakatani.
